!macro NSIS_HOOK_PREINSTALL
  ; Remove only retired Zapret Manager resources left by a prior installer.
  ; User data under LocalAppData is intentionally never touched here.
  Delete "$INSTDIR\engine\README.md"
  Delete "$INSTDIR\engine\local\service.bat"
  Delete "$INSTDIR\engine\local\general.bat"
  Delete "$INSTDIR\engine\local\general (ALT2).bat"
  Delete "$INSTDIR\engine\local\general (ALT3).bat"
  Delete "$INSTDIR\engine\local\general (ALT4).bat"
  Delete "$INSTDIR\engine\local\general (ALT5).bat"
  Delete "$INSTDIR\engine\local\general (ALT6).bat"
  Delete "$INSTDIR\engine\local\general (ALT7).bat"
  Delete "$INSTDIR\engine\local\general (ALT8).bat"
  Delete "$INSTDIR\engine\local\general (ALT9).bat"
  Delete "$INSTDIR\engine\local\general (ALT10).bat"
  Delete "$INSTDIR\engine\local\general (ALT11).bat"
  Delete "$INSTDIR\engine\local\general (ALT12).bat"
  Delete "$INSTDIR\engine\local\general (FAKE TLS AUTO ALT).bat"
  Delete "$INSTDIR\engine\local\general (FAKE TLS AUTO ALT2).bat"
  Delete "$INSTDIR\engine\local\general (FAKE TLS AUTO ALT3).bat"
  Delete "$INSTDIR\engine\local\general (SIMPLE FAKE).bat"
  Delete "$INSTDIR\engine\local\general (SIMPLE FAKE ALT).bat"
  Delete "$INSTDIR\engine\local\general (SIMPLE FAKE ALT2).bat"
  Delete "$INSTDIR\engine\local\web (TELEGRAM PHASE0).bat"
  Delete "$INSTDIR\engine\local\web (TELEGRAM RUNTIME DUP).bat"
  Delete "$INSTDIR\engine\local\web (TELEGRAM RUNTIME SYNDATA).bat"
  Delete "$INSTDIR\engine\local\web (TELEGRAM RUNTIME WSSIZE).bat"
  Delete "$INSTDIR\engine\local\web (TELEGRAM).bat"
  Delete "$INSTDIR\engine\local\web (WHATSAPP RUNTIME SYNDATA).bat"
  Delete "$INSTDIR\engine\local\web (WHATSAPP RUNTIME WSSIZE).bat"
  Delete "$INSTDIR\engine\local\web (WHATSAPP).bat"
  Delete "$INSTDIR\engine\local\bin\tls_clienthello_4pda_to.bin"
  Delete "$INSTDIR\engine\local\lists\ipset-telegram-phase0.txt"
  Delete "$INSTDIR\engine\local\lists\list-telegram.txt"
  Delete "$INSTDIR\engine\local\lists\list-telegram-web.txt"
  Delete "$INSTDIR\engine\local\lists\list-whatsapp.txt"
  Delete "$INSTDIR\engine\local\lists\list-whatsapp-web.txt"
  Delete "$INSTDIR\profiles\common.json"
  Delete "$INSTDIR\profiles\telegram.json"
  Delete "$INSTDIR\profiles\whatsapp.json"
  Delete "$INSTDIR\strategies\stable\common.json"
  Delete "$INSTDIR\strategies\stable\telegram.json"
  Delete "$INSTDIR\strategies\stable\whatsapp.json"
  Delete "$INSTDIR\strategies\experimental\common.json"
  Delete "$INSTDIR\strategies\experimental\telegram.json"
  Delete "$INSTDIR\strategies\experimental\whatsapp.json"
!macroend
